name: CI/CD 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t my-flask-app .
          docker tag my-flask-app ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest

      - name: SSH into EC2 instance and pull Docker image
        run: |
          sudo apt update && sudo apt install -y sshpass
          sshpass -p "${{ secrets.EC2_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest
          sudo docker stop my-flask-app || true
          sudo docker rm my-flask-app || true
          sudo docker run -d -p 5000:5000 --name my-flask-app ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest
          EOF
