name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt update && sudo apt install -y sshpass

      - name: SSH into EC2 instance and pull Docker image
        run: |
          sshpass -p "${{ secrets.EC2_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest
          docker run -d -p 80:5000 --name my-flask-app ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest
          EOF
